# Copyright 2019 baicells Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: install mysql
  apt:
    name: mysql-server
    state: present
    update_cache: no

- name: add user mysql
  user:
    name: mysql
    group: mysql
    shell: /sbin/nologin
    state: present

- name: touch my.cnf
  tags: ["never"]
  copy:
    src: roles/install_5gc/files/my.cnf
    dest: /etc/mysql/
    owner: mysql
    group: mysql
    mode: 0644
    backup: yes
    force: yes 

- name: touch mysql.service
  tags: ["never"]
  copy:
    src: roles/install_5gc/files/mysql.service
    dest: /lib/systemd/system/
    owner: mysql
    group: mysql
    mode: 0644
    backup: yes
    force: yes

- name: mod /etc/profile
  tags: ["never"]
  lineinfile:
    path: /etc/profile
    regexp: '^export PATH=\$PATH:\/usr\/local\/mysql\/bin\/'
    line: 'export PATH=$PATH:/usr/local/mysql/bin/'
    #backrefs: yes

- name: source /etc/profile
  tags: ["never"]
  shell: "source /etc/profile"
  args: 
    executable: /bin/bash 
