# Copyright 2019 baicells Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: install jdk
  apt:
    name: roles/install_5gc/files/jdk1.8_1.8.0162-1_amd64.deb
    state: present
    update_cache: no

- name: add "JAVA_HOME" to /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: '^export JAVA_HOME=\/usr\/java\/jdk1.8.0_162'
    line: 'export JAVA_HOME=/usr/java/jdk1.8.0_162'

- name: add "JRE_HOME" to /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: '^export JRE_HOME=\/usr\/java\/jdk1.8.0_162\/jre'
    line: 'export JRE_HOME=/usr/java/jdk1.8.0_162/jre'

- name: add "CLASSPATH" to /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: '^export CLASSPATH=$CLASSPATH:$JAVA_HOME\/lib\/dt.jar:$JAVA_HOME\/lib\/tools.jar'
    line: 'export CLASSPATH=$CLASSPATH:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar'

- name: add "JAVA_HOME/bin" to /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: '^export PATH=$PATH:$JAVA_HOME\/bin\/'
    line: 'export PATH=$PATH:$JAVA_HOME/bin/'
